environment:
  DO_ACCESS_KEY: ${DO_ACCESS_KEY}
  DO_SECRET_KEY: ${DO_SECRET_KEY}
  DO_SPACES_REGION: ${DO_SPACES_REGION}
  DO_SPACES_BUCKET: ${DO_SPACES_BUCKET}

packages:
  - name: pcm-to-mp3
    actions:
      - name: pcm-to-mp3
        runtime: 'python:default'