environment:
  DO_ACCESS_KEY: ${DO_ACCESS_KEY}
  DO_SECRET_KEY: ${DO_SECRET_KEY}
  DO_SPACES_REGION: ${DO_SPACES_REGION}
  DO_SPACES_BUCKET: ${DO_SPACES_BUCKET}

packages:
  - name: img-to-thumb
    actions:
      - name: img-to-thumb
        runtime: 'python:default'